config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'categories/index'
  end

  devise_for :users

  root 'pages#index'
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'

  namespace 'api', defaults: { format: :json }  do
    namespace 'v1' do

      #   UsersController
      delete 'users' => 'users#destroy'
      post 'users' => 'users#create'
      post 'users/authorize' => 'users#authorize'
      post 'users/sponsor' => 'users#sponsor'
      get 'users' => 'users#show'
      get 'users/sponsor-ids' => 'users#sponsor_ids'
      patch 'users' => 'users#update'

      #   WalletsController
      get 'wallets' => 'wallets#index'


      #   SettingsController
      get 'settings' => 'settings#index'
      get 'settings/game' => 'settings#game'

      #   LimitsController
      get 'limits' => 'limits#index'

      #   TransactionsController
      patch 'transactions/video1' => 'transactions#video1'
      patch 'transactions/video2' => 'transactions#video2'
      get 'transactions/active' => 'transactions#active'
      get 'transactions/passive' => 'transactions#passive'
      get 'transactions/screen-lock' => 'transactions#screen_lock'

      #   QuizAttemptsController
      post 'quiz-attempts' => 'quiz_attempts#create'

      #   QuizQuestionAttemptsController
      get 'quiz-question-attempts/:id' => 'quiz_question_attempts#show'
      patch 'quiz-question-attempts/:id' => 'quiz_question_attempts#update'

      #   OffersController
      get 'offers' => 'offers#index'

      #   TasksController
      get 'tasks' => 'tasks#index'
      post 'tasks/:id/submit' => 'tasks#submit'

      #   ProductsController
      get 'products' => 'products#index'

      #   TrackingController
      get 'tracking/phono' => 'tracking#phono'
      get 'tracking/icubeswire' => 'tracking#icubeswire'
      get 'tracking/conversionx' => 'tracking#conversionx'
      get 'tracking/vcommission' => 'tracking#vcommission'
      get 'tracking/rubicko' => 'tracking#rubicko'
      post 'tracking/instamojo' => 'tracking#instamojo'
      get 'tracking/tapjoy' => 'tracking#tapjoy'
      get 'tracking/vnative' => 'tracking#vnative'
      post 'tracking/game' => 'tracking#game'
      post 'tracking/task' => 'tracking#task_firebase'
      post 'tracking/wallpaper' => 'tracking#task_wallpaper'
      get 'tracking/payu' => 'tracking#payu'
      post 'tracking/outside' => 'tracking#outside'

      #   UserLevelsController
      get 'user-levels' => 'user_levels#index'
      get 'user-levels/upline' => 'user_levels#upline'
      get 'user-levels/:id' => 'user_levels#show'
      post 'user-levels/search' => 'user_levels#search'

      #   DealsController
      get 'deals' => 'deals#index'

      #   DealUploadsController
      post 'deal-uploads/:id' => 'deal_uploads#create'

      #   QuizWinnersController
      get 'quiz-winners' => 'quiz_winners#index'

      #   RedeemsController
      scope 'redeems' do
        get '/' => 'redeems#check_time'
        post 'paypal' => 'redeems#paypal'
        post 'paytm' => 'redeems#paytm'
        post 'bank' => 'redeems#bank'
        post 'payza' => 'redeems#payza'
        post 'bkash' => 'redeems#bkash'
        post 'ed_ads' => 'redeems#ed_ads'
      end

      get 'you-tubes' => 'you_tubes#index'

      #   NotificationsController
      get 'notifications' => 'notifications#index'
    end

    namespace 'app' do
      scope 'categories' do
        get '/' => 'categories#index'
        get 'homepage' => 'categories#homepage'
        get ':id' => 'categories#show'
      end

      get 'wallpapers/:id' => 'wallpapers#show'
    end
  end

  namespace 'admin' do

    #   DashboardsController
    get '/' => 'dashboard#index'
    post '/closing' => 'dashboard#closing', as: :closing
    get 'choose-quiz-winner' => 'dashboard#quiz_winner', as: :choose_quiz_winner
    post 'choose-quiz-winner' => 'dashboard#choose_quiz_winners'

    #   UsersController
    get 'users' => 'users#index', as: :users
    post 'users' => 'users#create'
    get 'users/new' => 'users#new', as: :new_user
    get 'users/:id' => 'users#show', as: :user
    patch 'users/:id' => 'users#update'
    get 'users/:id/levels/:level' => 'users#level', as: :user_level
    post 'users/:id/approve' => 'users#approve', as: :approve_user
    get 'users/chart-data/:days' => 'users#chart_data', as: :user_chart_data

    #   QuizQuestionsController
    get 'quiz-questions' => 'quiz_questions#index', as: :quiz_questions
    post 'quiz-questions' => 'quiz_questions#create'
    get 'quiz-questions/:id/edit' => 'quiz_questions#edit', as: :edit_quiz_question
    patch 'quiz-questions/:id' => 'quiz_questions#update', as: :quiz_question

    #   QuizAttemptsController
    get 'quiz-attempts' => 'quiz_attempts#index', as: :quiz_attempts
    get 'quiz-attempts/:id' => 'quiz_attempts#show', as: :quiz_attempt
    delete 'quiz-attempts/:id' => 'quiz_attempts#destroy'

    #   OffersController
    get 'offers' => 'offers#index', as: :offers
    post 'offers' => 'offers#create'
    get 'offers/new' => 'offers#new', as: :new_offer
    get 'offers/:id' => 'offers#show', as: :offer
    patch 'offers/:id' => 'offers#update'
    get 'offers/:id/edit' => 'offers#edit', as: :edit_offer
    delete 'offers/:id' => 'offers#destroy'

    #   DealsController
    get 'deals' => 'deals#index', as: :deals
    post 'deals' => 'deals#create'
    get 'deals/new' => 'deals#new', as: :new_deal
    get 'deals/:id' => 'deals#show', as: :deal
    patch 'deals/:id' => 'deals#update'
    get 'deals/:id/edit' => 'deals#edit', as: :edit_deal
    delete 'deals/:id' => 'deals#destroy'

    #   ProductsController
    get 'products' => 'products#index', as: :products
    post 'products' => 'products#create'
    get 'products/new' => 'products#new', as: :new_product
    get 'products/:id' => 'products#show', as: :product
    patch 'products/:id' => 'products#update'
    get 'products/:id/edit' => 'products#edit', as: :edit_product
    delete 'products/:id' => 'products#destroy'

    #   TasksController
    get 'tasks' => 'tasks#index', as: :tasks
    get 'tasks/upload-csv' => 'tasks#new_csv', as: :upload_csv_task
    post 'tasks/upload-csv' => 'tasks#create_csv'
    post 'tasks' => 'tasks#create'
    get 'tasks/new' => 'tasks#new', as: :new_task
    get 'tasks/:id/edit' => 'tasks#edit', as: :edit_task
    get 'tasks/:id' => 'tasks#show', as: :task
    patch 'tasks/:id' => 'tasks#update'
    delete 'tasks/:id' => 'tasks#destroy'

    #   SettingsController
    get 'settings' => 'settings#index', as: :settings
    patch 'settings' => 'settings#update'

    #   TaskSubmitsController
    get 'task-submits' => 'task_submits#index', as: :task_submits
    get 'task-submits/:id' => 'task_submits#show', as: :task_submit
    post 'task-submits/:id' => 'task_submits#approve', as: :approve_task_submit
    patch 'task-submits/:id' => 'task_submits#unapprove', as: :unapprove_task_submit
    delete 'task-submits/:id' => 'task_submits#destroy'

    #   DealUploadsController
    get 'deal-uploads' => 'deal_uploads#index', as: :deal_uploads
    get 'deal-uploads/:id' => 'deal_uploads#show', as: :deal_upload
    post 'deal-uploads/:id/approve' => 'deal_uploads#approve', as: :approve_deal_upload
    post 'deal-uploads/:id/decline' => 'deal_uploads#decline', as: :decline_deal_upload
    delete 'deal-uploads/:id' => 'deal_uploads#destroy'

    #   ConversionsController
    get 'conversions' => 'conversions#index', as: :conversions
    post 'conversions/:id/approve' => 'conversions#approve', as: :approve_conversion

    #   TransactionsController
    scope 'transactions' do
      get 'credit/:id' => 'transactions#credit', as: :credit_transaction
      post 'credit/:id' => 'transactions#credit_save'
      get 'debit/:id' => 'transactions#debit', as: :debit_transaction
      post 'debit/:id' => 'transactions#debit_save'
      get '/' => 'transactions#all', as: :all_transactions
      get '/:id/:type' => 'transactions#index', as: :transactions
    end

    #   RedeemsController
    scope 'redeems' do
      get '/' => 'redeems#index', as: :redeems
      get 'export' => 'redeems#export', as: :export_redeems
      post 'export' => 'redeems#download_export'
      get '/user/:id' => 'redeems#user', as: :user_redeems
      get '/:id/decline' => 'redeems#decline_form', as: :decline_reason_redeem
      post '/:id' => 'redeems#approve', as: :approve_redeem
      delete '/:id' => 'redeems#decline', as: :decline_redeem
      get '/:id' => 'redeems#show', as: :redeem
    end

    # QuizWinnersController
    scope 'quiz-winners' do
      get '/' => 'quiz_winners#index', as: :quiz_winners
      get '/:id' => 'quiz_winners#show', as: :quiz_winner
    end

    #   RewardTasksController
    scope 'reward-tasks' do
      get '/' => 'reward_tasks#index', as: :reward_tasks
      get '/:id' => 'reward_tasks#show', as: :reward_task
    end

    scope 'categories' do
      get '/' => 'categories#index', as: :categories
      post '/' => 'categories#create'
      get 'new' => 'categories#new', as: :new_category
      get ':id/edit' => 'categories#edit', as: :edit_category
      patch ':id' => 'categories#update', as: :category
      delete ':id' => 'categories#destroy'
    end

    scope 'wallpapers' do
      get '/' => 'wallpapers#index', as: :wallpapers
      get 'new' => 'wallpapers#new', as: :new_wallpaper
      post '/' => 'wallpapers#create'
      get ':id/edit' => 'wallpapers#edit', as: :edit_wallpaper
      patch ':id' => 'wallpapers#update', as: :wallpaper
      delete ':id' => 'wallpapers#destroy'
    end

    resources :you_tubes

    scope 'notifications' do
      get '/' => 'notifications#index', as: :notifications
      post '/' => 'notifications#create'
      delete '/:id' => 'notifications#destroy'
      get '/new' => 'notifications#new', as: :new_notification
    end

    scope 'custom-files' do
      get '/' => 'custom_files#index', as: :custom_files
      post '/' => 'custom_files#create'

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  image       :string(255)
#  price       :decimal(10, )
#  description :text(65535)
#  link        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  active      :boolean          default(FALSE)
#  slug        :string(255)
#  amount      :decimal(10, 4)
#

class Product < ApplicationRecord

  validates :name, :image, :price, :description, :link, presence: true

  mount_uploader :image, OfferImageUploader

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout 'admin'

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductDatatable.new(view_context) }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = 'Product Added'
      redirect_to admin_products_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update! product_params
      flash[:success] = 'Product Updated'
      redirect_to admin_product_path @product
    else
      flash[:error] = 'Please try again'
      render 'edit'
    end
  end

  def destroy
    if @product.destroy
      flash[:error] = 'Product deleted'
      redirect_to admin_products_path
    else
      flash[:error] = 'Please try again'
      redirect_back fallback_location: admin_products_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :price, :description, :link, :active, :slug, :amount)
  end

  def set_product
    @product = Product.find_by_id params[:id]
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::BaseController

  def index
    render json: Product.where(active: true).paginate(per_page: 9, page: params[:page])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%
url = @product.new_record? ? admin_products_path : admin_product_path(@product)
%>
<%= form_for @product, url: url do |f| %>
  <h5 class="form-header"><%= @product.new_record? ? 'New' : 'Edit' %> Product</h5>

  <% if @product.errors.full_messages.count > 0 %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <% @product.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :link %>
        <%= f.text_field :link, class: 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :slug %>
        <%= f.text_field :slug, class: 'form-control' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :coins %>
        <%= f.text_field :amount, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :active, class: 'form-check-input' %>
      Active
    </label>
  </div>

  <div class="form-buttons-w">
    <button class="btn btn-primary" type="submit"> Submit</button>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Admin</a></li>
        <li class="breadcrumb-item"><a href="<%= admin_products_path %>">Products</a></li>
        <li class="breadcrumb-item"><span>Edit Product</span></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="row">
            <div class="col-sm-12">
              <div class="element-wrapper">

                <%= render 'layouts/flash' %>

                <div class="element-box">
                  <%= render 'form' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/admin/products/index.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%= admin_products_path %>">Products</a></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper">
            <h6 class="element-header">Products</h6>

            <%= render 'layouts/flash' %>

            <div class="element-box">
              <h5 class="form-header">Products List</h5>
              <div class="form-desc">
                <a href="<%= admin_new_product_path %>" class="mr-2 mb-2 btn btn-outline-primary"> New Product</a>
              </div>
              <div class="table-responsive">
                <table id="products-table" width="100%" class="table table-striped table-lightfont" data-source="<%= admin_products_path %>">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Created At</th>
                    <th>Link</th>
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>
</body>

app/views/admin/products/new.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Admin</a></li>
        <li class="breadcrumb-item"><a href="<%= admin_products_path %>">Products</a></li>
        <li class="breadcrumb-item"><span>New Product</span></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="row">
            <div class="col-sm-12">
              <div class="element-wrapper">

                <%= render 'layouts/flash' %>

                <div class="element-box">
                  <%= render 'form' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/admin/products/show.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Admin</a></li>
        <li class="breadcrumb-item"><a href="<%= admin_products_path %>">Products</a></li>
        <li class="breadcrumb-item"><span>Product</span></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="row">
            <div class="col-sm-12">
              <div class="element-wrapper">
                <h6 class="element-header">Product</h6>
                <%= render 'layouts/flash' %>

                <div class="element-box">
                  <h5 class="form-header">Products List</h5>
                  <div class="form-desc">
                    <%= link_to 'Edit', admin_edit_product_path(@product), class: 'mr-2 mb-2 btn btn-outline-info' %>
                    <%= link_to 'Delete', admin_product_path(@product), class: 'mr-2 mb-2 btn btn-outline-danger', method: :delete, data: { confirm: 'Are yous sure?' } %>
                  </div>.

                  <div class="table-responsive">
                    <table class="table table-striped table-lightfont">
                      <tr>
                        <th>Name</th>
                        <td><%= @product.name %></td>
                      </tr>
                      <tr>
                        <th>Price</th>
                        <td><%= @product.price %></td>
                      </tr>
                      <tr>
                        <th>Image</th>
                        <td><%= image_tag @product.image %></td>
                      </tr>
                      <tr>
                        <th>Description</th>
                        <td><%= @product.description %></td>
                      </tr>
                      <tr>
                        <th>Link</th>
                        <td><%= @product.link %></td>
                      </tr>
                      <tr>
                        <th>Active</th>
                        <td><%= @product.active %></td>
                      </tr>
                    </table>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>