config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'categories/index'
  end

  devise_for :users

  root 'pages#index'
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'

  namespace 'api', defaults: { format: :json }  do
    namespace 'v1' do

      #   UsersController
      delete 'users' => 'users#destroy'
      post 'users' => 'users#create'
      post 'users/authorize' => 'users#authorize'
      post 'users/sponsor' => 'users#sponsor'
      get 'users' => 'users#show'
      get 'users/sponsor-ids' => 'users#sponsor_ids'
      patch 'users' => 'users#update'

      #   WalletsController
      get 'wallets' => 'wallets#index'


      #   SettingsController
      get 'settings' => 'settings#index'
      get 'settings/game' => 'settings#game'

      #   LimitsController
      get 'limits' => 'limits#index'

      #   TransactionsController
      patch 'transactions/video1' => 'transactions#video1'
      patch 'transactions/video2' => 'transactions#video2'
      get 'transactions/active' => 'transactions#active'
      get 'transactions/passive' => 'transactions#passive'
      get 'transactions/screen-lock' => 'transactions#screen_lock'

      #   QuizAttemptsController
      post 'quiz-attempts' => 'quiz_attempts#create'

      #   QuizQuestionAttemptsController
      get 'quiz-question-attempts/:id' => 'quiz_question_attempts#show'
      patch 'quiz-question-attempts/:id' => 'quiz_question_attempts#update'

      #   OffersController
      get 'offers' => 'offers#index'

      #   TasksController
      get 'tasks' => 'tasks#index'
      post 'tasks/:id/submit' => 'tasks#submit'

      #   ProductsController
      get 'products' => 'products#index'

      #   TrackingController
      get 'tracking/phono' => 'tracking#phono'
      get 'tracking/icubeswire' => 'tracking#icubeswire'
      get 'tracking/conversionx' => 'tracking#conversionx'
      get 'tracking/vcommission' => 'tracking#vcommission'
      get 'tracking/rubicko' => 'tracking#rubicko'
      post 'tracking/instamojo' => 'tracking#instamojo'
      get 'tracking/tapjoy' => 'tracking#tapjoy'
      get 'tracking/vnative' => 'tracking#vnative'
      post 'tracking/game' => 'tracking#game'
      post 'tracking/task' => 'tracking#task_firebase'
      post 'tracking/wallpaper' => 'tracking#task_wallpaper'
      get 'tracking/payu' => 'tracking#payu'
      post 'tracking/outside' => 'tracking#outside'

      #   UserLevelsController
      get 'user-levels' => 'user_levels#index'
      get 'user-levels/upline' => 'user_levels#upline'
      get 'user-levels/:id' => 'user_levels#show'
      post 'user-levels/search' => 'user_levels#search'

      #   DealsController
      get 'deals' => 'deals#index'

      #   DealUploadsController
      post 'deal-uploads/:id' => 'deal_uploads#create'

      #   QuizWinnersController
      get 'quiz-winners' => 'quiz_winners#index'

      #   RedeemsController
      scope 'redeems' do
        get '/' => 'redeems#check_time'
        post 'paypal' => 'redeems#paypal'
        post 'paytm' => 'redeems#paytm'
        post 'bank' => 'redeems#bank'
        post 'payza' => 'redeems#payza'
        post 'bkash' => 'redeems#bkash'
        post 'ed_ads' => 'redeems#ed_ads'
      end

      get 'you-tubes' => 'you_tubes#index'

      #   NotificationsController
      get 'notifications' => 'notifications#index'
    end

    namespace 'app' do
      scope 'categories' do
        get '/' => 'categories#index'
        get 'homepage' => 'categories#homepage'
        get ':id' => 'categories#show'
      end

      get 'wallpapers/:id' => 'wallpapers#show'
    end
  end

  namespace 'admin' do

    #   DashboardsController
    get '/' => 'dashboard#index'
    post '/closing' => 'dashboard#closing', as: :closing
    get 'choose-quiz-winner' => 'dashboard#quiz_winner', as: :choose_quiz_winner
    post 'choose-quiz-winner' => 'dashboard#choose_quiz_winners'

    #   UsersController
    get 'users' => 'users#index', as: :users
    post 'users' => 'users#create'
    get 'users/new' => 'users#new', as: :new_user
    get 'users/:id' => 'users#show', as: :user
    patch 'users/:id' => 'users#update'
    get 'users/:id/levels/:level' => 'users#level', as: :user_level
    post 'users/:id/approve' => 'users#approve', as: :approve_user
    get 'users/chart-data/:days' => 'users#chart_data', as: :user_chart_data

    #   QuizQuestionsController
    get 'quiz-questions' => 'quiz_questions#index', as: :quiz_questions
    post 'quiz-questions' => 'quiz_questions#create'
    get 'quiz-questions/:id/edit' => 'quiz_questions#edit', as: :edit_quiz_question
    patch 'quiz-questions/:id' => 'quiz_questions#update', as: :quiz_question

    #   QuizAttemptsController
    get 'quiz-attempts' => 'quiz_attempts#index', as: :quiz_attempts
    get 'quiz-attempts/:id' => 'quiz_attempts#show', as: :quiz_attempt
    delete 'quiz-attempts/:id' => 'quiz_attempts#destroy'

    #   OffersController
    get 'offers' => 'offers#index', as: :offers
    post 'offers' => 'offers#create'
    get 'offers/new' => 'offers#new', as: :new_offer
    get 'offers/:id' => 'offers#show', as: :offer
    patch 'offers/:id' => 'offers#update'
    get 'offers/:id/edit' => 'offers#edit', as: :edit_offer
    delete 'offers/:id' => 'offers#destroy'

    #   DealsController
    get 'deals' => 'deals#index', as: :deals
    post 'deals' => 'deals#create'
    get 'deals/new' => 'deals#new', as: :new_deal
    get 'deals/:id' => 'deals#show', as: :deal
    patch 'deals/:id' => 'deals#update'
    get 'deals/:id/edit' => 'deals#edit', as: :edit_deal
    delete 'deals/:id' => 'deals#destroy'

    #   ProductsController
    get 'products' => 'products#index', as: :products
    post 'products' => 'products#create'
    get 'products/new' => 'products#new', as: :new_product
    get 'products/:id' => 'products#show', as: :product
    patch 'products/:id' => 'products#update'
    get 'products/:id/edit' => 'products#edit', as: :edit_product
    delete 'products/:id' => 'products#destroy'

    #   TasksController
    get 'tasks' => 'tasks#index', as: :tasks
    get 'tasks/upload-csv' => 'tasks#new_csv', as: :upload_csv_task
    post 'tasks/upload-csv' => 'tasks#create_csv'
    post 'tasks' => 'tasks#create'
    get 'tasks/new' => 'tasks#new', as: :new_task
    get 'tasks/:id/edit' => 'tasks#edit', as: :edit_task
    get 'tasks/:id' => 'tasks#show', as: :task
    patch 'tasks/:id' => 'tasks#update'
    delete 'tasks/:id' => 'tasks#destroy'

    #   SettingsController
    get 'settings' => 'settings#index', as: :settings
    patch 'settings' => 'settings#update'

    #   TaskSubmitsController
    get 'task-submits' => 'task_submits#index', as: :task_submits
    get 'task-submits/:id' => 'task_submits#show', as: :task_submit
    post 'task-submits/:id' => 'task_submits#approve', as: :approve_task_submit
    patch 'task-submits/:id' => 'task_submits#unapprove', as: :unapprove_task_submit
    delete 'task-submits/:id' => 'task_submits#destroy'

    #   DealUploadsController
    get 'deal-uploads' => 'deal_uploads#index', as: :deal_uploads
    get 'deal-uploads/:id' => 'deal_uploads#show', as: :deal_upload
    post 'deal-uploads/:id/approve' => 'deal_uploads#approve', as: :approve_deal_upload
    post 'deal-uploads/:id/decline' => 'deal_uploads#decline', as: :decline_deal_upload
    delete 'deal-uploads/:id' => 'deal_uploads#destroy'

    #   ConversionsController
    get 'conversions' => 'conversions#index', as: :conversions
    post 'conversions/:id/approve' => 'conversions#approve', as: :approve_conversion

    #   TransactionsController
    scope 'transactions' do
      get 'credit/:id' => 'transactions#credit', as: :credit_transaction
      post 'credit/:id' => 'transactions#credit_save'
      get 'debit/:id' => 'transactions#debit', as: :debit_transaction
      post 'debit/:id' => 'transactions#debit_save'
      get '/' => 'transactions#all', as: :all_transactions
      get '/:id/:type' => 'transactions#index', as: :transactions
    end

    #   RedeemsController
    scope 'redeems' do
      get '/' => 'redeems#index', as: :redeems
      get 'export' => 'redeems#export', as: :export_redeems
      post 'export' => 'redeems#download_export'
      get '/user/:id' => 'redeems#user', as: :user_redeems
      get '/:id/decline' => 'redeems#decline_form', as: :decline_reason_redeem
      post '/:id' => 'redeems#approve', as: :approve_redeem
      delete '/:id' => 'redeems#decline', as: :decline_redeem
      get '/:id' => 'redeems#show', as: :redeem
    end

    # QuizWinnersController
    scope 'quiz-winners' do
      get '/' => 'quiz_winners#index', as: :quiz_winners
      get '/:id' => 'quiz_winners#show', as: :quiz_winner
    end

    #   RewardTasksController
    scope 'reward-tasks' do
      get '/' => 'reward_tasks#index', as: :reward_tasks
      get '/:id' => 'reward_tasks#show', as: :reward_task
    end

    scope 'categories' do
      get '/' => 'categories#index', as: :categories
      post '/' => 'categories#create'
      get 'new' => 'categories#new', as: :new_category
      get ':id/edit' => 'categories#edit', as: :edit_category
      patch ':id' => 'categories#update', as: :category
      delete ':id' => 'categories#destroy'
    end

    scope 'wallpapers' do
      get '/' => 'wallpapers#index', as: :wallpapers
      get 'new' => 'wallpapers#new', as: :new_wallpaper
      post '/' => 'wallpapers#create'
      get ':id/edit' => 'wallpapers#edit', as: :edit_wallpaper
      patch ':id' => 'wallpapers#update', as: :wallpaper
      delete ':id' => 'wallpapers#destroy'
    end

    resources :you_tubes

    scope 'notifications' do
      get '/' => 'notifications#index', as: :notifications
      post '/' => 'notifications#create'
      delete '/:id' => 'notifications#destroy'
      get '/new' => 'notifications#new', as: :new_notification
    end

    scope 'custom-files' do
      get '/' => 'custom_files#index', as: :custom_files
      post '/' => 'custom_files#create'

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController

  layout 'admin'

  def all
    respond_to do |format|
      format.html
      format.json { render json: TransactionDatatable.new(view_context) }
    end
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: TransactionDatatable.new(view_context) }
    end
  end

  def credit
    @transaction = Transaction.new
  end

  def credit_save
    Transaction.transaction do
      user = User.find_by_id params[:id]
      if user
        @transaction = Transaction.new custom_transaction_params
        @transaction.direction = Transaction::DIRECTION[:credit]
        @transaction.user = user
        @transaction.from_user = user
        @transaction.from_user_status = user.status
        if @transaction.save
          user.wallet.add_money @transaction.amount
          flash[:success] = "User credited with amount #{@transaction.amount}"
          redirect_to admin_user_path(user)
        else
          render 'credit'
        end
      else
        flash[:error] = 'User not found'
        redirect_to admin_users_path
      end
    end
  end

  def debit
    @transaction = Transaction.new
  end

  def debit_save
    Transaction.transaction do
      user = User.find_by_id params[:id]
      if user
        @transaction = Transaction.new custom_transaction_params
        amount = @transaction.amount
        @transaction.amount = -@transaction.amount
        @transaction.direction = Transaction::DIRECTION[:credit]
        @transaction.user = user
        @transaction.from_user = user
        @transaction.from_user_status = user.status
        if @transaction.save
          user.wallet.deduct_money amount
          flash[:success] = "User debited with amount #{@transaction.amount}"
          redirect_to admin_user_path(user)
        else
          render 'credit'
        end
      else
        flash[:error] = 'User not found'
        redirect_to admin_users_path
      end
    end
  end

  private

  def custom_transaction_params
    params.require(:transaction).permit(:amount, :category, :data)
  end

end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < Api::BaseController

  def video1
    limit = get_limit
    if limit.video1 < Setting.ppv1_limit.to_i
      limit.video1 += 1
      limit.save

      real_amount = Setting.ppv1_amount.to_f
      self_amount = real_amount.to_f * 0.85

      transaction = Transaction.create(
                     user: current_user,
                     direction: Transaction::DIRECTION[:credit],
                     category: Transaction::CATEGORY[:video1],
                     amount: self_amount,
                     from_user: current_user,
                     from_user_status: current_user.status
      )
      transaction.user.wallet.add_money transaction.amount
      transaction.distribute_upline real_amount

      render json: limit and return
    end
    render json: {
        status: false
    }
  end

  def video2
    limit = get_limit
    if limit.video2 < Setting.ppv2_limit.to_i
      limit.video2 += 1
      limit.save

      real_amount = Setting.ppv2_amount.to_f
      self_amount = real_amount.to_f * 0.85

      transaction = Transaction.create(
          user: current_user,
          direction: Transaction::DIRECTION[:credit],
          category: Transaction::CATEGORY[:video2],
          amount: self_amount,
          from_user: current_user
      )
      transaction.user.wallet.add_money transaction.amount
      transaction.distribute_upline real_amount

      render json: limit and return
    end
    render json: {
        status: false
    }
  end

  def active
    transactions = Transaction.where(user: current_user, from_user_status: User::STATUS[:approved]).order(created_at: :desc)
    serialized = []
    transactions.each do |transaction|
      serialized << TransactionSerializer.new(transaction)
    end
    render json: { transactions: serialized }
  end

  def passive
    transactions = Transaction.where(user: current_user, from_user_status: User::STATUS[:verified]).order(created_at: :desc)
    serialized = []
    transactions.each do |transaction|
      serialized << TransactionSerializer.new(transaction)
    end
    render json: { transactions: serialized }
  end

  def screen_lock
    transactions = Transaction.where(user: current_user, category: Transaction::CATEGORY[:screen_lock]).order(created_at: :desc)
    serialized = []
    transactions.each do |transaction|
      serialized << TransactionSerializer.new(transaction)
    end
    render json: { transactions: serialized }
  end

end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/admin/transactions/_form.html.erb
<%= form_for @transaction, url: '' do |f| %>
  <% if @transaction.errors.full_messages.count > 0 %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <% @transaction.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :amount %>
        <%= f.text_field :amount, type: 'number', class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :category %>
        <%= f.collection_select :category, Transaction::CATEGORY_REVERSE, :first, :second, {}, { class: 'form-control', id: 'transaction-category-dynamic' } %>
      </div>
    </div>
  </div>

  <div class="form-group" id="custom-message" style="display: none;">
    <%= f.label :data %>
    <%= f.text_field :data, class: 'form-control' %>
  </div>

  <div class="form-buttons-w">
    <button class="btn btn-primary" type="submit"> Submit</button>
  </div>
<% end %>

app/views/admin/transactions/all.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Home</a></li>
        <li class="breadcrumb-item"><a href="">Transactions</a></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper"><h6 class="element-header">Transactions</h6>
            <div class="element-box">
              <h5 class="form-header">Transactions List</h5>
              <div class="table-responsive">
                <table id="transactions-table" width="100%" class="table table-striped table-lightfont" data-source="<%= admin_all_transactions_path %>">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Amount</th>
                    <th>Category</th>
                    <th>Direction</th>
                    <th>From User</th>
                    <th>Data</th>
                    <th>User</th>
                    <th>Created At</th>
                  </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>
</body>

app/views/admin/transactions/credit.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%=  %>">Credit Transaction</a></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper"><h6 class="element-header">Credit Transaction</h6>
            <div class="element-box">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>
</body>

app/views/admin/transactions/debit.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Home</a></li>
        <li class="breadcrumb-item"><a href="<%=  %>">Debit Transaction</a></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper"><h6 class="element-header">Debit Transaction</h6>
            <div class="element-box">

              <%= render 'form' %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>
</body>

app/views/admin/transactions/index.html.erb
<body>
<div class="all-wrapper menu-top">
  <div class="layout-w">

    <%= render 'layouts/header' %>

    <div class="content-w">
      <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= admin_path %>">Home</a></li>
        <li class="breadcrumb-item"><a href="">Transactions</a></li>
      </ul>

      <div class="content-i">
        <div class="content-box">
          <div class="element-wrapper"><h6 class="element-header">Transactions</h6>
            <div class="element-box">
              <h5 class="form-header">Transactions List</h5>
              <div class="table-responsive">
                <table id="transactions-table" width="100%" class="table table-striped table-lightfont" data-source="<%= admin_transactions_path %>">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Amount</th>
                    <th>Category</th>
                    <th>Direction</th>
                    <th>From User</th>
                    <th>Data</th>
                    <th>User</th>
                    <th>Created At</th>
                  </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="display-type"></div>
</div>
</body>